version: "3.7"
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: relay
      POSTGRES_HOST_AUTH_METHOD: trust

  relay:
    image: ghcr.io/relay-io/relay:sha-e749824
    environment:
      - DATABASE_URL=postgres://username:pass@postgres:5432/relay?sslmode=disable
      - HTTP_PORT=8080
      - RUST_LOG=debug
    ports:
      - "8080:8080"
    command: >
      bash -c "
          while ! echo -n > /dev/tcp/postgres/5432; do
            echo 'waiting for postgres'
            sleep 0.1
          done
          relay
      "
    depends_on:
      - postgres