name: Lint & Test
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-v1-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-v1-go-

      - name: Test
        run: make test.ci
        env:
          RELAY_URL: "http://localhost:8080"

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
